author: Kotaro Yoshimatsu
blogName: ktrysmt.log
userid: ktrysmt
locale: ja_JP
description: "SREとかセキュリティガバナンスとか"
url: 'https://ktrysmt.github.io'
permalink: /blog/:title/
exclude:
  - google1d3f81208ecf60fb.html
#
# blogName: "ktrysmt.log"
#
# aboutPage: true
#
plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

#
# markdown: kramdown
# kramdown:
#   syntax_highlighter_opts:
#     disable : true
#
# baseurl: /
#
# domain_name: 'https://ktrysmt.github.io'
#
# url: 'https://ktrysmt.github.io'
#
# authorTwitter:  'ktrysmt'
# authorFullName: 'Kotaro Yoshimatsu'
# authorRealName: 'Kotaro Yoshimatsu'
#

